export default {
    user: state => state.user,
    isAuthenticated: state => state.isAuthenticated,
    token: state => state.token,
    loginFormErrors: state => state.loginFormErrors,
    loginResponseError: state => state.loginResponseError,
    todo: state => state.todo,
    todoPagination: state => state.todoPagination,
    todoError: state => state.todoError,
    todoCurrentLink: state => state.todoCurrentLink,
    inprogress: state => state.inprogress,
    inprogressPagination: state => state.inprogressPagination,
    inprogressError: state => state.inprogressError,
    inprogressCurrentLink: state => state.inprogressCurrentLink,
    done: state => state.done,
    donePagination: state => state.donePagination,
    doneError: state => state.doneError,
    doneCurrentLink: state => state.doneCurrentLink,
}
